services:
  dev_postgres:
    image: postgres:16-alpine
    container_name: dev_postgres_db
    restart: unless-stopped 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dev_pgdata:/var/lib/postgresql/data

  nextjs-app:
    build:
      context: .
      dockerfile: .docker/nextjs/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - dev_postgres


volumes:
  dev_pgdata:
    driver: local
