services:
    dev_postgres:
        image: postgres:16-alpine
        container_name: dev_postgres_db
        restart: unless-stopped
        env_file:
            - .env.dev
        ports:
            - "5432:5432"
        volumes:
            - dev_pgdata:/var/lib/postgresql/data

    nextjs-app:
        container_name: nextjs-app
        build:
            context: .
            dockerfile: .docker/nextjs/dev/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./nextjs-app:/app
            - /app/node_modules
        depends_on:
            - dev_postgres

volumes:
    dev_pgdata:
        driver: local
