services:
    nextjs-app:
        container_name: nextjs-app
        build:
            context: .
            dockerfile: .docker/nextjs/dev/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./nextjs-app:/app
            - /app/node_modules
        depends_on:
            - dev_postgres

volumes:
    dev_pgdata:
        driver: local
