services:
  nextjs-app:
    build:
      context: .
      dockerfile: .docker/nextjs/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
